package org.cossbow.feng.ast.oop;

import org.cossbow.feng.ast.Position;
import org.cossbow.feng.ast.Symbol;
import org.cossbow.feng.ast.TypeDefinition;
import org.cossbow.feng.ast.TypeDomain;
import org.cossbow.feng.ast.attr.Modifier;
import org.cossbow.feng.ast.gen.TypeParameters;

/**
 * Base class for built-in type definitions that are not defined in source code
 * but are generated by the compiler during monomorphization (arrays, tuples).
 * <p>
 * Unlike {@link ObjectDefinition}, built-in types have no inheritance,
 * no vtable, and no user-defined methods.
 */
abstract
public class BuiltinTypeDefinition extends TypeDefinition {

    protected BuiltinTypeDefinition(Position pos,
                                    Symbol symbol,
                                    TypeParameters generic) {
        super(pos, Modifier.empty(), symbol, generic, TypeDomain.STRUCT);
    }

    @Override
    public boolean newable() {
        return true;
    }
}
